LogTime yes
Foreground yes
TCPSocket 3310
TCPAddr 0.0.0.0
MaxThreads 2
MaxQueue 8
ConcurrentDatabaseReload no
StreamMaxLength 100M
MaxFileSize 100M
MaxScanSize 150M
MaxRecursion 10
MaxFiles 10000
CommandReadTimeout 120
ReadTimeout 120
DatabaseDirectory /var/lib/clamav
